=== AdrianFG-UO307424/LaVuelta2026-AdrianFernandez/xml/etapa.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name ="TipoDecimalPositivo">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name ="TipoLatitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90.0"/>
			<xs:maxInclusive value="90.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name ="TipoLongitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180.0"/>
			<xs:maxInclusive value="180.0"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="numero" />
				<xs:element ref="longitud" />
				<xs:element ref="fecha" />
				<xs:element ref="tiempo_ganador" />
				<xs:element ref="velocidad_media" />
				<xs:element ref="desnivel" />
				<xs:element ref="ciudad_inicio" />
				<xs:element ref="ciudad_fin" />
				<xs:element ref="tipo" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="sonidos" />
				<xs:element ref="salida" />
				<xs:element ref="meta" />
				<xs:element ref="hitos" />
				<xs:element ref="puntos_anonimos" />
				<xs:element ref="clasificacion_etapa" />
				<xs:element ref="clasificacion_general" />
				<xs:element ref="clasificacion_equipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombre" type="xs:string" />

	<xs:element name="numero">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="21"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoDecimalPositivo">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="tiempo_ganador" type="xs:duration" />
	
	<xs:element name="velocidad_media">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoDecimalPositivo">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoDecimalPositivo">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ciudad_inicio" type="xs:string" />
	<xs:element name="ciudad_fin" type="xs:string" />

	<xs:element name="tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="llana"/>
				<xs:enumeration value="montaña"/>
				<xs:enumeration value="media montaña"/>
				<xs:enumeration value="contrarreloj individual"/>
				<xs:enumeration value="contrarreloj por equipos"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	
	<xs:element name="sonidos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="sonido" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sonido" type="xs:string" />
	
	<xs:element name="salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="meta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud_geo" />
				<xs:element ref="latitud_geo" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="longitud_geo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoLongitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="latitud_geo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoLatitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="hitos">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="puerto_montana" />
				<xs:element ref="sprint" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="puerto_montana">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="tipo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="primera" />
						<xs:enumeration value="segunda" />
						<xs:enumeration value="tercera" />
						<xs:enumeration value="especial" />
						<xs:enumeration value="bonificado" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sprint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="tipo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="intermedio" />
						<xs:enumeration value="bonificado" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="TipoDecimalPositivo">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="puntos_anonimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="punto_anonimo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="punto_anonimo">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="nombre_punto" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombre_punto" type="xs:string" />
	
	<xs:element name="clasificacion_etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs ="3" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificacion_general">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs ="3" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificacion_equipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs ="3" ref="equipo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="posicion" />
				<xs:element ref="corredor" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia_tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="equipo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="posicion" />
				<xs:element ref="nombre_equipo" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia_tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="posicion">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="corredor" type="xs:string" />
	<xs:element name="nombre_equipo" type="xs:string" />
	<xs:element name="diferencia_tiempo" type="xs:duration" />
</xs:schema>

=== AdrianFG-UO307424/LaVuelta2026-AdrianFernandez/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
    
    <nombre>Alcossebre - Castelló</nombre>
    <numero>6</numero>
    <longitud unidad="km">177.5</longitud>
    <fecha>2026-08-27</fecha>
    <tiempo_ganador>PT4H30M00S</tiempo_ganador>
    <velocidad_media unidad="km/h">39.4</velocidad_media>
    <desnivel unidad="metros">3094</desnivel>
    <ciudad_inicio>Alcossebre</ciudad_inicio>
    <ciudad_fin>Castelló</ciudad_fin>
    <tipo>media montaña</tipo>

    <referencias>
        <referencia>Libro de Ruta Oficial La Vuelta 26</referencia>
        <referencia>Dos</referencia>
        <referencia>Tres</referencia>  
	</referencias>

    <fotografias>
        <fotografia>etapa6.jpg</fotografia>
    </fotografias>
    <videos>
        <video>etapa6.mp4</video>
    </videos>
    <sonidos>
        <sonido>etapa6.mp3</sonido>
    </sonidos>

    <salida>
        <coordenadas>
            <longitud_geo unidad="grados">0.2810</longitud_geo>
            <latitud_geo unidad="grados">40.2511</latitud_geo>
            <altitud unidad="metros">62</altitud>
        </coordenadas>
    </salida>
    <meta>
        <coordenadas>
            <longitud_geo unidad="grados">-0.0295</longitud_geo>
            <latitud_geo unidad="grados">39.9748</latitud_geo>
            <altitud unidad="metros">23</altitud>
        </coordenadas>
    </meta>

    <hitos>
        <puerto_montana tipo="segunda">
            <coordenadas>
                <longitud_geo unidad="grados">0.0280</longitud_geo>
                <latitud_geo unidad="grados">40.3130</latitud_geo>
                <altitud unidad="metros">839</altitud>
            </coordenadas>
            <distancia unidad="km">44.6</distancia>
        </puerto_montana>
        <puerto_montana tipo="tercera">
            <coordenadas>
                <longitud_geo unidad="grados">0.0410</longitud_geo>
                <latitud_geo unidad="grados">40.2860</latitud_geo>
                <altitud unidad="metros">790</altitud>
            </coordenadas>
            <distancia unidad="km">66.1</distancia>
        </puerto_montana>
        <sprint tipo="intermedio">
            <coordenadas>
                <longitud_geo unidad="grados">0.0640</longitud_geo>
                <latitud_geo unidad="grados">40.0540</latitud_geo>
                <altitud unidad="metros">14</altitud>
            </coordenadas>
            <distancia unidad="km">120.1</distancia>
        </sprint>
        <puerto_montana tipo="segunda">
            <coordenadas>
                <longitud_geo unidad="grados">0.0290</longitud_geo>
                <latitud_geo unidad="grados">40.0760</latitud_geo>
                <altitud unidad="metros">422</altitud>
            </coordenadas>
            <distancia unidad="km">128.5</distancia>
        </puerto_montana>
        <puerto_montana tipo="primera">
            <coordenadas>
                <longitud_geo unidad="grados">0.0320</longitud_geo>
                <latitud_geo unidad="grados">40.0850</latitud_geo>
                <altitud unidad="metros">713</altitud>
            </coordenadas>
            <distancia unidad="km">158.8</distancia>
        </puerto_montana>
    </hitos>

    <puntos_anonimos>
        <punto_anonimo>
            <nombre_punto>Cruce N-340</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.2700</longitud_geo>
                <latitud_geo unidad="grados">40.2600</latitud_geo>
                <altitud unidad="metros">62</altitud>
            </coordenadas>
            <distancia unidad="km">1.9</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Alcalà de Xivert</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.2220</longitud_geo>
                <latitud_geo unidad="grados">40.3020</latitud_geo>
                <altitud unidad="metros">151</altitud>
            </coordenadas>
            <distancia unidad="km">6.3</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Les Coves de Vinromà</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.1230</longitud_geo>
                <latitud_geo unidad="grados">40.2660</latitud_geo>
                <altitud unidad="metros">182</altitud>
            </coordenadas>
            <distancia unidad="km">21.4</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Cruce izda. La Torre</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0800</longitud_geo>
                <latitud_geo unidad="grados">40.2600</latitud_geo>
                <altitud unidad="metros">250</altitud>
            </coordenadas>
            <distancia unidad="km">29.2</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>La Torre d'en Doménec</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0690</longitud_geo>
                <latitud_geo unidad="grados">40.2620</latitud_geo>
                <altitud unidad="metros">303</altitud>
            </coordenadas>
            <distancia unidad="km">30.3</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>La Serratella</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0300</longitud_geo>
                <latitud_geo unidad="grados">40.3000</latitud_geo>
                <altitud unidad="metros">800</altitud>
            </coordenadas>
            <distancia unidad="km">42.6</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Albocàsser</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0230</longitud_geo>
                <latitud_geo unidad="grados">40.3570</latitud_geo>
                <altitud unidad="metros">527</altitud>
            </coordenadas>
            <distancia unidad="km">52.0</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Mas de Sant Pau</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0200</longitud_geo>
                <latitud_geo unidad="grados">40.3200</latitud_geo>
                <altitud unidad="metros">480</altitud>
            </coordenadas>
            <distancia unidad="km">55.1</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Cruce izda. La Serra</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0150</longitud_geo>
                <latitud_geo unidad="grados">40.2800</latitud_geo>
                <altitud unidad="metros">600</altitud>
            </coordenadas>
            <distancia unidad="km">61.5</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Mas de Cervera</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0150</longitud_geo>
                <latitud_geo unidad="grados">40.2700</latitud_geo>
                <altitud unidad="metros">650</altitud>
            </coordenadas>
            <distancia unidad="km">62.0</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>La Serra d'en Galceran</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0100</longitud_geo>
                <latitud_geo unidad="grados">40.2500</latitud_geo>
                <altitud unidad="metros">700</altitud>
            </coordenadas>
            <distancia unidad="km">68.7</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Benlloc</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0260</longitud_geo>
                <latitud_geo unidad="grados">40.2090</latitud_geo>
                <altitud unidad="metros">310</altitud>
            </coordenadas>
            <distancia unidad="km">79.0</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Vall d'Alba</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0300</longitud_geo>
                <latitud_geo unidad="grados">40.1800</latitud_geo>
                <altitud unidad="metros">250</altitud>
            </coordenadas>
            <distancia unidad="km">85.5</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Rotonda izda. Cabanes</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0350</longitud_geo>
                <latitud_geo unidad="grados">40.1700</latitud_geo>
                <altitud unidad="metros">260</altitud>
            </coordenadas>
            <distancia unidad="km">87.0</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Rotonda dcha. Cabanes</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0380</longitud_geo>
                <latitud_geo unidad="grados">40.1600</latitud_geo>
                <altitud unidad="metros">260</altitud>
            </coordenadas>
            <distancia unidad="km">88.4</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Cabanes</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0410</longitud_geo>
                <latitud_geo unidad="grados">40.1570</latitud_geo>
                <altitud unidad="metros">263</altitud>
            </coordenadas>
            <distancia unidad="km">93.3</distancia>
        </punto_anonimo>
