=== AdrianFG-UO307424/LaVuelta2026-AdrianFernandez/LaVuelta2026/xml/etapa.dtd
<!ELEMENT etapa (nombre, numero, longitud, fecha, tiempo_ganador, velocidad_media, desnivel, ciudad_inicio, ciudad_fin, tipo, referencias, fotografias, videos, sonidos, salida, meta, hitos, puntos_anonimos, clasificacion_etapa, clasificacion_general, clasificacion_equipos)>

<!-- Datos básicos -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tiempo_ganador (#PCDATA)>
<!ELEMENT velocidad_media (#PCDATA)>
<!ATTLIST velocidad_media unidad CDATA #REQUIRED>
<!ELEMENT desnivel (#PCDATA)>
<!ATTLIST desnivel unidad CDATA #REQUIRED>
<!ELEMENT ciudad_inicio (#PCDATA)>
<!ELEMENT ciudad_fin (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>

<!-- Referencias y Multimedia -->
<!ELEMENT referencias (referencia, referencia, referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT fotografias (fotografia+)>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT sonidos (sonido+)>
<!ELEMENT sonido (#PCDATA)>

<!-- Coordenadas -->
<!ELEMENT salida (coordenadas)>
<!ELEMENT meta (coordenadas)>
<!ELEMENT coordenadas (longitud_geo, latitud_geo, altitud)>
<!ELEMENT longitud_geo (#PCDATA)>
<!ATTLIST longitud_geo unidad CDATA #REQUIRED>
<!ELEMENT latitud_geo (#PCDATA)>
<!ATTLIST latitud_geo unidad CDATA #REQUIRED>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidad CDATA #REQUIRED>

<!-- Hitos y Puntos Anonimos -->
<!ELEMENT hitos (puerto_montana | sprint)*>
<!ELEMENT puerto_montana (coordenadas, distancia)>
<!ATTLIST puerto_montana tipo (primera|segunda|tercera|especial|bonificado) #REQUIRED>
<!ELEMENT sprint (coordenadas, distancia)>
<!ATTLIST sprint tipo (intermedio|bonificado) #REQUIRED>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>

<!ELEMENT puntos_anonimos (punto_anonimo*)>
<!ELEMENT punto_anonimo (nombre_punto?, coordenadas, distancia)>
<!ELEMENT nombre_punto (#PCDATA)>

<!-- Clasificaciones -->
<!ELEMENT clasificacion_etapa (clasificado, clasificado, clasificado)>
<!ELEMENT clasificacion_general (clasificado, clasificado, clasificado)>
<!ELEMENT clasificacion_equipos (equipo, equipo, equipo)>

<!ELEMENT clasificado (posicion, corredor, diferencia_tiempo?)>
<!ELEMENT equipo (posicion, nombre_equipo, diferencia_tiempo?)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT corredor (#PCDATA)>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ELEMENT diferencia_tiempo (#PCDATA)>

=== AdrianFG-UO307424/LaVuelta2026-AdrianFernandez/LaVuelta2026/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">
<etapa>
    <nombre>Alcossebre a Castelló</nombre>
    <numero>6</numero>
    <longitud unidad="km">177.5</longitud>
    <fecha>2026-08-27</fecha>
    <tiempo_ganador>04:30:00</tiempo_ganador>
    <velocidad_media unidad="km/h">39.4</velocidad_media>
    <desnivel unidad="metros">3094</desnivel>
    <ciudad_inicio>Alcossebre</ciudad_inicio>
    <ciudad_fin>Castelló</ciudad_fin>
    <tipo>media montaña</tipo>

    <!-- Referencias -->
    <referencias>
        <referencia>Libro de Ruta Oficial La Vuelta 26</referencia>
        <referencia>Dos</referencia>
        <referencia>Tres</referencia>
    </referencias>

    <!-- Multimedia -->
    <fotografias>
        <fotografia>etapa6.jpg</fotografia>
    </fotografias>
    <videos>
        <video>etapa6.mp4</video>
    </videos>
    <sonidos>
        <sonido>etapa6.mp3</sonido>
    </sonidos>

    <!-- Lugares de Salida y Meta-->
    <salida>
        <coordenadas>
            <longitud_geo unidad="grados">0.2810</longitud_geo>
            <latitud_geo unidad="grados">40.2511</latitud_geo>
            <altitud unidad="metros">62</altitud>
        </coordenadas>
    </salida>
    <meta>
        <coordenadas>
            <longitud_geo unidad="grados">-0.0295</longitud_geo>
            <latitud_geo unidad="grados">39.9748</latitud_geo>
            <altitud unidad="metros">23</altitud>
        </coordenadas>
    </meta>

    <!-- Hitos de la Etapa -->
    <hitos>
        <puerto_montana tipo="segunda">
            <coordenadas>
                <longitud_geo unidad="grados">0.0280</longitud_geo>
                <latitud_geo unidad="grados">40.3130</latitud_geo>
                <altitud unidad="metros">839</altitud>
            </coordenadas>
            <distancia unidad="km">44.6</distancia>
        </puerto_montana>
        <puerto_montana tipo="tercera">
            <coordenadas>
                <longitud_geo unidad="grados">0.0410</longitud_geo>
                <latitud_geo unidad="grados">40.2860</latitud_geo>
                <altitud unidad="metros">790</altitud>
            </coordenadas>
            <distancia unidad="km">66.1</distancia>
        </puerto_montana>
        <sprint tipo="intermedio">
            <coordenadas>
                <longitud_geo unidad="grados">0.0640</longitud_geo>
                <latitud_geo unidad="grados">40.0540</latitud_geo>
                <altitud unidad="metros">22</altitud>
            </coordenadas>
            <distancia unidad="km">120.1</distancia>
        </sprint>
        <puerto_montana tipo="segunda">
            <coordenadas>
                <longitud_geo unidad="grados">0.0290</longitud_geo>
                <latitud_geo unidad="grados">40.0760</latitud_geo>
                <altitud unidad="metros">422</altitud>
            </coordenadas>
            <distancia unidad="km">128.5</distancia>
        </puerto_montana>
        <puerto_montana tipo="primera">
            <coordenadas>
                <longitud_geo unidad="grados">0.0320</longitud_geo>
                <latitud_geo unidad="grados">40.0850</latitud_geo>
                <altitud unidad="metros">713</altitud>
            </coordenadas>
            <distancia unidad="km">158.8</distancia>
        </puerto_montana>
    </hitos>

    <!-- Puntos Anónimos -->
    <puntos_anonimos>
        <punto_anonimo>
            <nombre_punto>Cruce N-340</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.2700</longitud_geo>
                <latitud_geo unidad="grados">40.2600</latitud_geo>
                <altitud unidad="metros">62</altitud>
            </coordenadas>
            <distancia unidad="km">1.9</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Alcalà de Xivert</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.2220</longitud_geo>
                <latitud_geo unidad="grados">40.3020</latitud_geo>
                <altitud unidad="metros">151</altitud>
            </coordenadas>
            <distancia unidad="km">6.3</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Les Coves de Vinromà</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.1230</longitud_geo>
                <latitud_geo unidad="grados">40.2660</latitud_geo>
                <altitud unidad="metros">182</altitud>
            </coordenadas>
            <distancia unidad="km">21.4</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Cruce izda. La Torre</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0800</longitud_geo>
                <latitud_geo unidad="grados">40.2600</latitud_geo>
                <altitud unidad="metros">250</altitud>
            </coordenadas>
            <distancia unidad="km">29.2</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>La Torre d'en Doménec</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0690</longitud_geo>
                <latitud_geo unidad="grados">40.2620</latitud_geo>
                <altitud unidad="metros">303</altitud>
            </coordenadas>
            <distancia unidad="km">30.3</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>La Serratella</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0300</longitud_geo>
                <latitud_geo unidad="grados">40.3000</latitud_geo>
                <altitud unidad="metros">800</altitud>
            </coordenadas>
            <distancia unidad="km">42.6</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Albocàsser</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0230</longitud_geo>
                <latitud_geo unidad="grados">40.3570</latitud_geo>
                <altitud unidad="metros">527</altitud>
            </coordenadas>
            <distancia unidad="km">52.0</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Mas de Sant Pau</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0200</longitud_geo>
                <latitud_geo unidad="grados">40.3200</latitud_geo>
                <altitud unidad="metros">480</altitud>
            </coordenadas>
            <distancia unidad="km">55.1</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Cruce izda. La Serra</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0150</longitud_geo>
                <latitud_geo unidad="grados">40.2800</latitud_geo>
                <altitud unidad="metros">600</altitud>
            </coordenadas>
            <distancia unidad="km">61.5</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Mas de Cervera</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0150</longitud_geo>
                <latitud_geo unidad="grados">40.2700</latitud_geo>
                <altitud unidad="metros">650</altitud>
            </coordenadas>
            <distancia unidad="km">62.0</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>La Serra d'en Galceran</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0100</longitud_geo>
                <latitud_geo unidad="grados">40.2500</latitud_geo>
                <altitud unidad="metros">700</altitud>
            </coordenadas>
            <distancia unidad="km">68.7</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Benlloc</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0260</longitud_geo>
                <latitud_geo unidad="grados">40.2090</latitud_geo>
                <altitud unidad="metros">310</altitud>
            </coordenadas>
            <distancia unidad="km">79.0</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Vall d'Alba</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0300</longitud_geo>
                <latitud_geo unidad="grados">40.1800</latitud_geo>
                <altitud unidad="metros">250</altitud>
            </coordenadas>
            <distancia unidad="km">85.5</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Rotonda izda. Cabanes</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0350</longitud_geo>
                <latitud_geo unidad="grados">40.1700</latitud_geo>
                <altitud unidad="metros">260</altitud>
            </coordenadas>
            <distancia unidad="km">87.0</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Rotonda dcha. Cabanes</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0380</longitud_geo>
                <latitud_geo unidad="grados">40.1600</latitud_geo>
                <altitud unidad="metros">260</altitud>
            </coordenadas>
            <distancia unidad="km">88.4</distancia>
        </punto_anonimo>
        <punto_anonimo>
            <nombre_punto>Cabanes</nombre_punto>
            <coordenadas>
                <longitud_geo unidad="grados">0.0410</longitud_geo>
                <latitud_geo unidad="grados">40.1570</latitud_geo>
                <altitud unidad="metros">263</altitud>
            </coordenadas>
            <distancia unidad="km">93.3</distancia>
